version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: pokelike_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7p3aoDnBAMf%#$SZpzCP
      POSTGRES_DB: PokeLikeDb
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pokelike-network

  api:
    image: maxitect/pokelike-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PokeLikeDbContext=Host=db;Port=5432;Database=PokeLikeDb;Username=postgres;Password=7p3aoDnBAMf%#$SZpzCP
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    platform: linux/amd64
    restart: always
    networks:
      - pokelike-network

networks:
  pokelike-network:
    driver: bridge
