apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: pokelike-api

build:
  artifacts:
  - image: europe-west2-docker.pkg.dev/${PROJECT_ID}/pokelike-artifacts/pokelike-artifacts
    docker:
      dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - kubernetes/postgres-deployment.yaml
      - kubernetes/postgres-service.yaml
      - kubernetes/api-deployment.yaml
      - kubernetes/api-service.yaml

profiles:
- name: gcb
  build:
    googleCloudBuild: {} 