apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokelike-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokelike-api
  template:
    metadata:
      labels:
        app: pokelike-api
    spec:
      containers:
        - name: pokelike-api
          image: europe-west2-docker.pkg.dev/poke-like-api/pokelike-artifacts/pokelike-artifacts:${GITHUB_SHA}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "25m"
              memory: "128Mi"
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__PokeLikeDbContext
              value: "Host=postgres;Port=5432;Database=PokeLikeDb;Username=postgres;Password=welovepokemon"
