apiVersion: v1
kind: Service
metadata:
  name: pokelike-api
  annotations:
    cloud.google.com/backend-config: '{"default": "pokelike-backend-config"}'
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
  selector:
    app: pokelike-api
