apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokelike-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "pokelike-ip"
    kubernetes.io/ingress.allow-http: "true"
spec:
  ingressClassName: "gce"
  rules:
    - host: "pokelike.34.160.33.103.nip.io"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: pokelike-api
                port:
                  number: 80
