name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  PROJECT_ID: poke-like-api
  GKE_CLUSTER: pokelike-cluster
  GKE_ZONE: europe-west2-a
  IMAGE: pokelike-artifacts
  NODE_POOL_NAME: preemptible-pool

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Google Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Setup GCloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: Build and Push Image
        run: |
          docker build -t europe-west2-docker.pkg.dev/$PROJECT_ID/$IMAGE/$IMAGE:$GITHUB_SHA .
          docker push europe-west2-docker.pkg.dev/$PROJECT_ID/$IMAGE/$IMAGE:$GITHUB_SHA

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Create and Wait for Node Pool
        run: |
          if ! gcloud container node-pools describe $NODE_POOL_NAME \
            --cluster $GKE_CLUSTER \
            --zone $GKE_ZONE; then
            gcloud container node-pools create $NODE_POOL_NAME \
              --cluster=$GKE_CLUSTER \
              --preemptible \
              --machine-type=e2-small \
              --num-nodes=2 \  # Changed from 1 to 2
              --zone=$GKE_ZONE
          fi
          # Wait for node pool to be ready
          until kubectl get nodes -l cloud.google.com/gke-preemptible=true | grep -q "Ready"; do
            echo "Waiting for preemptible nodes to be ready..."
            sleep 10
          done
          # Additional check for node capacity
          kubectl describe nodes | grep -A 5 "Allocated resources"

      - name: Delete Existing Resources
        run: |
          kubectl delete -f kubernetes/ --ignore-not-found
          kubectl wait --for=delete deployment/pokelike-api --timeout=60s || true
          kubectl wait --for=delete deployment/postgres --timeout=60s || true

      - name: Update API Image Tag
        run: |
          sed -i "s|:v:${GITHUB_SHA}|" kubernetes/api-deployment.yaml

      - name: Deploy All Resources
        run: |
          # Apply all resources
          kubectl apply -f kubernetes/

          # Wait for core deployments
          kubectl wait --for=condition=available deployment/postgres --timeout=180s
          kubectl wait --for=condition=available deployment/pokelike-api --timeout=180s

          # Wait for ingress
          kubectl wait --for=condition=Ready ingress/pokelike-ingress --timeout=300s
