name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  PROJECT_ID: poke-like-api
  IMAGE: pokelike-artifacts
  REGION: europe-west2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Google Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Setup GCloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and Push API Image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$IMAGE/$IMAGE:$GITHUB_SHA .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$IMAGE/$IMAGE:$GITHUB_SHA

      - name: Setup Network
        run: |
          if ! gcloud compute networks describe pokelike-network; then
            gcloud compute networks create pokelike-network --subnet-mode=auto
          fi

      - name: Create VPC Connector
        run: |
          gcloud compute networks vpc-access connectors create pokelike-connector \
            --network=pokelike-network \
            --region=$REGION \
            --range=10.8.0.0/28 || true

      - name: Deploy Postgres
        run: |
          gcloud run deploy postgres \
            --image=postgres:latest \
            --platform=managed \
            --region=$REGION \
            --cpu=0.1 \
            --memory=256Mi \
            --service-account=github-actions@poke-like-api.iam.gserviceaccount.com \
            --set-env-vars="POSTGRES_DB=PokeLikeDb,POSTGRES_USER=postgres,POSTGRES_PASSWORD=welovepokemon" \
            --vpc-connector=pokelike-connector

      - name: Deploy API
        run: |
          gcloud run deploy pokelike-api \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/$IMAGE/$IMAGE:$GITHUB_SHA \
            --platform=managed \
            --region=$REGION \
            --cpu=0.1 \
            --memory=256Mi \
            --service-account=github-actions@poke-like-api.iam.gserviceaccount.com \
            --set-env-vars="ConnectionStrings__PokeLikeDbContext=Host=postgres;Port=5432;Database=PokeLikeDb;Username=postgres;Password=welovepokemon" \
            --allow-unauthenticated \
            --vpc-connector=pokelike-connector
